### ISSUE TITLE
Fix linux reboot

### ISSUE THREAD

**Issue by wojtas-marcin** [MarvellEmbeddedProcessors/edk2#3] opened 2016-04-07 14:55 UTC
Possibly the issue is caused by lack of psci mem reservation. Reference by Haim:
"the function is called psci_reserve_mem and it's located in arch/arm/cpu/armv8/cpu-dt.c
see patch "psci: re-enable psci configuration when running in EL2" which updated the reserve mem addresses of ATF
(note (to help with the patch review): when running u-boot from ATF, we consider the psci as not enabled in u-boot)"

**Comment by dabros-jan** [comment] 2016-06-16 01:42
This bug isn't related with lack of psci mem reservation. Issue is caused by improper handling of EFI_RUNTIME_SERVICES. It was proved by creating WA - after removing efi_reset call from reboot process in Linux kernel, platform reboot works properly. efi_reset calls efi_reset_system function, which is one of runtime service provided by UEFI.

**Comment by dabros-jan** [comment] 2016-07-20 07:37
Fixed on
https://github.com/MarvellEmbeddedProcessors/edk2-open-platform/commits/sh-opp-2016.04-devel

**Closed as completed by dabros-jan** 2016-07-20 07:37 UTC
